import type { CliThemeInfo } from './theme-info';
import { DefaultThemes } from './default-themes';

export const DefaultThemeInfos: Record<string, CliThemeInfo> = {
    default: {
        theme: DefaultThemes.default,
        category: 'dark',
        tags: ['built-in'],
        description: 'Dark indigo theme with soft pastels',
    },
    classic: {
        theme: DefaultThemes.classic,
        category: 'dark',
        tags: ['built-in'],
        description: 'Classic Windows terminal palette',
    },
    dracula: {
        theme: DefaultThemes.dracula,
        category: 'dark',
        tags: ['popular'],
        description: 'Popular dark theme with vibrant colors',
    },
    monokai: {
        theme: DefaultThemes.monokai,
        category: 'dark',
        tags: ['popular'],
        description: 'Classic code editor dark theme',
    },
    solarizedDark: {
        theme: DefaultThemes.solarizedDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Ethan Schoonover\'s precision dark palette',
    },
    solarizedLight: {
        theme: DefaultThemes.solarizedLight,
        category: 'light',
        tags: ['popular'],
        description: 'Ethan Schoonover\'s precision light palette',
    },
    gruvboxDark: {
        theme: DefaultThemes.gruvboxDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Retro groove dark color scheme',
    },
    gruvboxLight: {
        theme: DefaultThemes.gruvboxLight,
        category: 'light',
        tags: ['popular'],
        description: 'Retro groove light color scheme',
    },
    nord: {
        theme: DefaultThemes.nord,
        category: 'dark',
        tags: ['popular'],
        description: 'Arctic, north-bluish clean palette',
    },
    oneDark: {
        theme: DefaultThemes.oneDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Atom\'s iconic dark theme',
    },
    material: {
        theme: DefaultThemes.material,
        category: 'dark',
        tags: ['popular'],
        description: 'Material Design inspired dark theme',
    },
    highContrastLight: {
        theme: DefaultThemes.highContrastLight,
        category: 'light',
        tags: ['accessibility'],
        description: 'High contrast light theme for accessibility',
    },
    tokyoNight: {
        theme: DefaultThemes.tokyoNight,
        category: 'dark',
        tags: ['popular'],
        description: 'Cool blue-purple dark theme',
    },
    catppuccinMocha: {
        theme: DefaultThemes.catppuccinMocha,
        category: 'dark',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel dark theme (warmest)',
    },
    catppuccinFrappe: {
        theme: DefaultThemes.catppuccinFrappe,
        category: 'dark',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel mid-dark theme',
    },
    catppuccinLatte: {
        theme: DefaultThemes.catppuccinLatte,
        category: 'light',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel light theme',
    },
    rosePine: {
        theme: DefaultThemes.rosePine,
        category: 'dark',
        tags: ['popular'],
        description: 'All natural pine, faux fur, and a bit of soho vibes',
    },
    rosePineDawn: {
        theme: DefaultThemes.rosePineDawn,
        category: 'light',
        tags: ['popular'],
        description: 'Rose Pine light variant',
    },
    kanagawa: {
        theme: DefaultThemes.kanagawa,
        category: 'dark',
        tags: ['popular'],
        description: 'Dark theme inspired by Katsushika Hokusai',
    },
    everforestDark: {
        theme: DefaultThemes.everforestDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Comfortable green-tinted dark theme',
    },
    everforestLight: {
        theme: DefaultThemes.everforestLight,
        category: 'light',
        tags: ['popular'],
        description: 'Comfortable green-tinted light theme',
    },
    ayuDark: {
        theme: DefaultThemes.ayuDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Simple, bright and elegant dark theme',
    },
    githubLight: {
        theme: DefaultThemes.githubLight,
        category: 'light',
        tags: ['popular'],
        description: 'GitHub\'s clean light interface theme',
    },
    cyberpunk: {
        theme: DefaultThemes.cyberpunk,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Neon-lit cyberpunk aesthetic',
    },
    retroGreen: {
        theme: DefaultThemes.retroGreen,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Classic green phosphor CRT monitor',
    },
    retroAmber: {
        theme: DefaultThemes.retroAmber,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Warm amber CRT monitor',
    },
    matrix: {
        theme: DefaultThemes.matrix,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Enter the Matrix - green on black',
    },
    synthwave: {
        theme: DefaultThemes.synthwave,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: '80s synthwave purple/pink aesthetic',
    },
    highContrastDark: {
        theme: DefaultThemes.highContrastDark,
        category: 'dark',
        tags: ['accessibility'],
        description: 'Maximum contrast dark theme',
    },
};
