import type { ITheme } from '@xterm/xterm';

export type CliTheme = ITheme;

type DefaultThemesType = {
    default: CliTheme;
    dracula: CliTheme;
    monokai: CliTheme;
    solarizedDark: CliTheme;
    solarizedLight: CliTheme;
    gruvboxDark: CliTheme;
    gruvboxLight: CliTheme;
    nord: CliTheme;
    oneDark: CliTheme;
    material: CliTheme;
    highContrastLight: CliTheme;
    tokyoNight: CliTheme;
    catppuccinMocha: CliTheme;
    catppuccinFrappe: CliTheme;
    rosePine: CliTheme;
    kanagawa: CliTheme;
    everforestDark: CliTheme;
    ayuDark: CliTheme;
    catppuccinLatte: CliTheme;
    rosePineDawn: CliTheme;
    everforestLight: CliTheme;
    githubLight: CliTheme;
    cyberpunk: CliTheme;
    retroGreen: CliTheme;
    retroAmber: CliTheme;
    matrix: CliTheme;
    synthwave: CliTheme;
    highContrastDark: CliTheme;
    yellow: CliTheme;
    [key: string]: CliTheme;
};

export const DefaultThemes = {
    default: {
        background: '#0c0c0c',
        foreground: '#cccccc',
        cursor: '#cccccc',
        selectionBackground: '#264f78',
        selectionForeground: '#ffffff',
        black: '#0c0c0c',
        red: '#c50f1f',
        green: '#13a10e',
        yellow: '#c19c00',
        blue: '#0037da',
        magenta: '#881798',
        cyan: '#3a96dd',
        white: '#cccccc',
        brightBlack: '#767676',
        brightRed: '#e74856',
        brightGreen: '#16c60c',
        brightYellow: '#f9f1a5',
        brightBlue: '#3b78ff',
        brightMagenta: '#b4009e',
        brightCyan: '#61d6d6',
        brightWhite: '#f2f2f2',
    },
    dracula: {
        background: '#282A36',
        foreground: '#F8F8F2',
        cursor: '#50FA7B',
        black: '#21222C',
        red: '#FF5555',
        green: '#50FA7B',
        yellow: '#F1FA8C',
        blue: '#BD93F9',
        magenta: '#FF79C6',
        cyan: '#8BE9FD',
        white: '#F8F8F2',
        brightBlack: '#6272A4',
        brightRed: '#FF6E6E',
        brightGreen: '#69FF94',
        brightYellow: '#FFFFA5',
        brightBlue: '#D6ACFF',
        brightMagenta: '#FF92D0',
        brightCyan: '#A4FFFF',
        brightWhite: '#FFFFFF',
    },
    monokai: {
        background: '#272822',
        foreground: '#F8F8F2',
        cursor: '#F8F8F0',
        black: '#272822',
        red: '#F92672',
        green: '#A6E22E',
        yellow: '#F4BF75',
        blue: '#66D9EF',
        magenta: '#AE81FF',
        cyan: '#A1EFE4',
        white: '#F8F8F2',
        brightBlack: '#75715E',
        brightRed: '#F92672',
        brightGreen: '#A6E22E',
        brightYellow: '#F4BF75',
        brightBlue: '#66D9EF',
        brightMagenta: '#AE81FF',
        brightCyan: '#A1EFE4',
        brightWhite: '#F9F8F5',
    },
    solarizedDark: {
        background: '#002B36',
        foreground: '#839496',
        cursor: '#93A1A1',
        black: '#073642',
        red: '#DC322F',
        green: '#859900',
        yellow: '#B58900',
        blue: '#268BD2',
        magenta: '#D33682',
        cyan: '#2AA198',
        white: '#EEE8D5',
        brightBlack: '#002B36',
        brightRed: '#CB4B16',
        brightGreen: '#586E75',
        brightYellow: '#657B83',
        brightBlue: '#839496',
        brightMagenta: '#6C71C4',
        brightCyan: '#93A1A1',
        brightWhite: '#FDF6E3',
    },
    solarizedLight: {
        background: '#FDF6E3',
        foreground: '#657B83',
        cursor: '#586E75',
        black: '#073642',
        red: '#DC322F',
        green: '#859900',
        yellow: '#B58900',
        blue: '#268BD2',
        magenta: '#D33682',
        cyan: '#2AA198',
        white: '#EEE8D5',
        brightBlack: '#002B36',
        brightRed: '#CB4B16',
        brightGreen: '#586E75',
        brightYellow: '#657B83',
        brightBlue: '#839496',
        brightMagenta: '#6C71C4',
        brightCyan: '#93A1A1',
        brightWhite: '#FDF6E3',
    },
    gruvboxDark: {
        background: '#282828',
        foreground: '#EBDBB2',
        cursor: '#EBDBB2',
        black: '#282828',
        red: '#CC241D',
        green: '#98971A',
        yellow: '#D79921',
        blue: '#458588',
        magenta: '#B16286',
        cyan: '#689D6A',
        white: '#A89984',
        brightBlack: '#928374',
        brightRed: '#FB4934',
        brightGreen: '#B8BB26',
        brightYellow: '#FABD2F',
        brightBlue: '#83A598',
        brightMagenta: '#D3869B',
        brightCyan: '#8EC07C',
        brightWhite: '#EBDBB2',
    },
    gruvboxLight: {
        background: '#FBF1C7',
        foreground: '#3C3836',
        cursor: '#3C3836',
        black: '#FBF1C7',
        red: '#9D0006',
        green: '#79740E',
        yellow: '#B57614',
        blue: '#076678',
        magenta: '#8F3F71',
        cyan: '#427B58',
        white: '#3C3836',
        brightBlack: '#D5C4A1',
        brightRed: '#AF3A03',
        brightGreen: '#B8BB26',
        brightYellow: '#FABD2F',
        brightBlue: '#83A598',
        brightMagenta: '#D3869B',
        brightCyan: '#8EC07C',
        brightWhite: '#EBDBB2',
    },
    nord: {
        background: '#2E3440',
        foreground: '#D8DEE9',
        cursor: '#88C0D0',
        black: '#3B4252',
        red: '#BF616A',
        green: '#A3BE8C',
        yellow: '#EBCB8B',
        blue: '#81A1C1',
        magenta: '#B48EAD',
        cyan: '#88C0D0',
        white: '#E5E9F0',
        brightBlack: '#4C566A',
        brightRed: '#BF616A',
        brightGreen: '#A3BE8C',
        brightYellow: '#EBCB8B',
        brightBlue: '#81A1C1',
        brightMagenta: '#B48EAD',
        brightCyan: '#8FBCBB',
        brightWhite: '#ECEFF4',
    },
    oneDark: {
        background: '#282C34',
        foreground: '#ABB2BF',
        cursor: '#528BFF',
        black: '#282C34',
        red: '#E06C75',
        green: '#98C379',
        yellow: '#E5C07B',
        blue: '#61AFEF',
        magenta: '#C678DD',
        cyan: '#56B6C2',
        white: '#ABB2BF',
        brightBlack: '#5C6370',
        brightRed: '#E06C75',
        brightGreen: '#98C379',
        brightYellow: '#E5C07B',
        brightBlue: '#61AFEF',
        brightMagenta: '#C678DD',
        brightCyan: '#56B6C2',
        brightWhite: '#FFFFFF',
    },
    material: {
        background: '#263238',
        foreground: '#ECEFF1',
        cursor: '#FFCC00',
        black: '#263238',
        red: '#F07178',
        green: '#C3E88D',
        yellow: '#FFCB6B',
        blue: '#82AAFF',
        magenta: '#C792EA',
        cyan: '#89DDFF',
        white: '#EEFFFF',
        brightBlack: '#546E7A',
        brightRed: '#F07178',
        brightGreen: '#C3E88D',
        brightYellow: '#FFCB6B',
        brightBlue: '#82AAFF',
        brightMagenta: '#C792EA',
        brightCyan: '#89DDFF',
        brightWhite: '#FFFFFF',
    },
    highContrastLight: {
        background: '#FFFACD',
        foreground: '#000000',
        cursor: '#FFA500',
        selectionBackground: '#FFD700',
        black: '#3B3A32',
        red: '#D32F2F',
        green: '#388E3C',
        yellow: '#FBC02D',
        blue: '#1976D2',
        magenta: '#8E24AA',
        cyan: '#0097A7',
        white: '#FFFFFF',
        brightBlack: '#616161',
        brightRed: '#FF5252',
        brightGreen: '#69F0AE',
        brightYellow: '#FFEB3B',
        brightBlue: '#64B5F6',
        brightMagenta: '#BA68C8',
        brightCyan: '#4DD0E1',
        brightWhite: '#FAFAFA',
    },
    tokyoNight: {
        background: '#1a1b26',
        foreground: '#c0caf5',
        cursor: '#c0caf5',
        selectionBackground: '#33467c',
        black: '#15161e',
        red: '#f7768e',
        green: '#9ece6a',
        yellow: '#e0af68',
        blue: '#7aa2f7',
        magenta: '#bb9af7',
        cyan: '#7dcfff',
        white: '#a9b1d6',
        brightBlack: '#414868',
        brightRed: '#f7768e',
        brightGreen: '#9ece6a',
        brightYellow: '#e0af68',
        brightBlue: '#7aa2f7',
        brightMagenta: '#bb9af7',
        brightCyan: '#7dcfff',
        brightWhite: '#c0caf5',
    },
    catppuccinMocha: {
        background: '#1e1e2e',
        foreground: '#cdd6f4',
        cursor: '#f5e0dc',
        selectionBackground: '#45475a',
        black: '#45475a',
        red: '#f38ba8',
        green: '#a6e3a1',
        yellow: '#f9e2af',
        blue: '#89b4fa',
        magenta: '#f5c2e7',
        cyan: '#94e2d5',
        white: '#bac2de',
        brightBlack: '#585b70',
        brightRed: '#f38ba8',
        brightGreen: '#a6e3a1',
        brightYellow: '#f9e2af',
        brightBlue: '#89b4fa',
        brightMagenta: '#f5c2e7',
        brightCyan: '#94e2d5',
        brightWhite: '#a6adc8',
    },
    catppuccinFrappe: {
        background: '#303446',
        foreground: '#c6d0f5',
        cursor: '#f2d5cf',
        selectionBackground: '#51576d',
        black: '#51576d',
        red: '#e78284',
        green: '#a6d189',
        yellow: '#e5c890',
        blue: '#8caaee',
        magenta: '#f4b8e4',
        cyan: '#81c8be',
        white: '#b5bfe2',
        brightBlack: '#626880',
        brightRed: '#e78284',
        brightGreen: '#a6d189',
        brightYellow: '#e5c890',
        brightBlue: '#8caaee',
        brightMagenta: '#f4b8e4',
        brightCyan: '#81c8be',
        brightWhite: '#a5adce',
    },
    rosePine: {
        background: '#191724',
        foreground: '#e0def4',
        cursor: '#524f67',
        selectionBackground: '#2a283e',
        black: '#26233a',
        red: '#eb6f92',
        green: '#31748f',
        yellow: '#f6c177',
        blue: '#9ccfd8',
        magenta: '#c4a7e7',
        cyan: '#ebbcba',
        white: '#e0def4',
        brightBlack: '#6e6a86',
        brightRed: '#eb6f92',
        brightGreen: '#31748f',
        brightYellow: '#f6c177',
        brightBlue: '#9ccfd8',
        brightMagenta: '#c4a7e7',
        brightCyan: '#ebbcba',
        brightWhite: '#e0def4',
    },
    kanagawa: {
        background: '#1f1f28',
        foreground: '#dcd7ba',
        cursor: '#c8c093',
        selectionBackground: '#2d4f67',
        black: '#16161d',
        red: '#c34043',
        green: '#76946a',
        yellow: '#c0a36e',
        blue: '#7e9cd8',
        magenta: '#957fb8',
        cyan: '#6a9589',
        white: '#c8c093',
        brightBlack: '#727169',
        brightRed: '#e82424',
        brightGreen: '#98bb6c',
        brightYellow: '#e6c384',
        brightBlue: '#7fb4ca',
        brightMagenta: '#938aa9',
        brightCyan: '#7aa89f',
        brightWhite: '#dcd7ba',
    },
    everforestDark: {
        background: '#2d353b',
        foreground: '#d3c6aa',
        cursor: '#d3c6aa',
        selectionBackground: '#543a48',
        black: '#475258',
        red: '#e67e80',
        green: '#a7c080',
        yellow: '#dbbc7f',
        blue: '#7fbbb3',
        magenta: '#d699b6',
        cyan: '#83c092',
        white: '#d3c6aa',
        brightBlack: '#475258',
        brightRed: '#e67e80',
        brightGreen: '#a7c080',
        brightYellow: '#dbbc7f',
        brightBlue: '#7fbbb3',
        brightMagenta: '#d699b6',
        brightCyan: '#83c092',
        brightWhite: '#d3c6aa',
    },
    ayuDark: {
        background: '#0b0e14',
        foreground: '#bfbdb6',
        cursor: '#e6b450',
        selectionBackground: '#1b3a4b',
        black: '#01060e',
        red: '#ea6c73',
        green: '#91b362',
        yellow: '#f9af4f',
        blue: '#53bdfa',
        magenta: '#fae994',
        cyan: '#90e1c6',
        white: '#c7c7c7',
        brightBlack: '#686868',
        brightRed: '#f07178',
        brightGreen: '#c2d94c',
        brightYellow: '#ffb454',
        brightBlue: '#59c2ff',
        brightMagenta: '#ffee99',
        brightCyan: '#95e6cb',
        brightWhite: '#ffffff',
    },
    catppuccinLatte: {
        background: '#eff1f5',
        foreground: '#4c4f69',
        cursor: '#dc8a78',
        selectionBackground: '#acb0be',
        black: '#5c5f77',
        red: '#d20f39',
        green: '#40a02b',
        yellow: '#df8e1d',
        blue: '#1e66f5',
        magenta: '#ea76cb',
        cyan: '#179299',
        white: '#acb0be',
        brightBlack: '#6c6f85',
        brightRed: '#d20f39',
        brightGreen: '#40a02b',
        brightYellow: '#df8e1d',
        brightBlue: '#1e66f5',
        brightMagenta: '#ea76cb',
        brightCyan: '#179299',
        brightWhite: '#bcc0cc',
    },
    rosePineDawn: {
        background: '#faf4ed',
        foreground: '#575279',
        cursor: '#9893a5',
        selectionBackground: '#dfdad9',
        black: '#f2e9e1',
        red: '#b4637a',
        green: '#286983',
        yellow: '#ea9d34',
        blue: '#56949f',
        magenta: '#907aa9',
        cyan: '#d7827e',
        white: '#575279',
        brightBlack: '#9893a5',
        brightRed: '#b4637a',
        brightGreen: '#286983',
        brightYellow: '#ea9d34',
        brightBlue: '#56949f',
        brightMagenta: '#907aa9',
        brightCyan: '#d7827e',
        brightWhite: '#575279',
    },
    everforestLight: {
        background: '#fdf6e3',
        foreground: '#5c6a72',
        cursor: '#5c6a72',
        selectionBackground: '#e6e2cc',
        black: '#5c6a72',
        red: '#f85552',
        green: '#8da101',
        yellow: '#dfa000',
        blue: '#3a94c5',
        magenta: '#df69ba',
        cyan: '#35a77c',
        white: '#dfddc8',
        brightBlack: '#708089',
        brightRed: '#f85552',
        brightGreen: '#8da101',
        brightYellow: '#dfa000',
        brightBlue: '#3a94c5',
        brightMagenta: '#df69ba',
        brightCyan: '#35a77c',
        brightWhite: '#e8e5d0',
    },
    githubLight: {
        background: '#ffffff',
        foreground: '#24292f',
        cursor: '#044289',
        selectionBackground: '#0969da33',
        black: '#24292f',
        red: '#cf222e',
        green: '#116329',
        yellow: '#4d2d00',
        blue: '#0969da',
        magenta: '#8250df',
        cyan: '#1b7c83',
        white: '#6e7781',
        brightBlack: '#57606a',
        brightRed: '#a40e26',
        brightGreen: '#1a7f37',
        brightYellow: '#633c01',
        brightBlue: '#218bff',
        brightMagenta: '#a475f9',
        brightCyan: '#3192aa',
        brightWhite: '#8c959f',
    },
    cyberpunk: {
        background: '#0a0a1a',
        foreground: '#0abdc6',
        cursor: '#ff2079',
        selectionBackground: '#1a1a3a',
        black: '#000000',
        red: '#ff2079',
        green: '#00ff9c',
        yellow: '#fed230',
        blue: '#0abdc6',
        magenta: '#ea00d9',
        cyan: '#0abdc6',
        white: '#c7c7c7',
        brightBlack: '#686868',
        brightRed: '#ff4a9e',
        brightGreen: '#3df5b6',
        brightYellow: '#fef465',
        brightBlue: '#3ff1de',
        brightMagenta: '#ff79f0',
        brightCyan: '#3ff1de',
        brightWhite: '#ffffff',
    },
    retroGreen: {
        background: '#0a0a0a',
        foreground: '#33ff00',
        cursor: '#33ff00',
        selectionBackground: '#1a3a1a',
        black: '#0a0a0a',
        red: '#ff0000',
        green: '#33ff00',
        yellow: '#ffff00',
        blue: '#0066ff',
        magenta: '#cc00ff',
        cyan: '#00ffff',
        white: '#33ff00',
        brightBlack: '#1a5c1a',
        brightRed: '#ff3333',
        brightGreen: '#66ff33',
        brightYellow: '#ffff66',
        brightBlue: '#3399ff',
        brightMagenta: '#e550ff',
        brightCyan: '#66ffff',
        brightWhite: '#66ff33',
    },
    retroAmber: {
        background: '#0a0a00',
        foreground: '#ffb000',
        cursor: '#ffb000',
        selectionBackground: '#3a2a00',
        black: '#0a0a00',
        red: '#ff0000',
        green: '#ffb000',
        yellow: '#ffcc00',
        blue: '#cc8800',
        magenta: '#ff8800',
        cyan: '#ffcc66',
        white: '#ffb000',
        brightBlack: '#665500',
        brightRed: '#ff3333',
        brightGreen: '#ffc033',
        brightYellow: '#ffdd33',
        brightBlue: '#ddaa33',
        brightMagenta: '#ffaa33',
        brightCyan: '#ffdd99',
        brightWhite: '#ffc033',
    },
    matrix: {
        background: '#000000',
        foreground: '#00ff41',
        cursor: '#00ff41',
        selectionBackground: '#003300',
        black: '#000000',
        red: '#00ff41',
        green: '#00ff41',
        yellow: '#00ff41',
        blue: '#00cc33',
        magenta: '#009926',
        cyan: '#00ff41',
        white: '#00ff41',
        brightBlack: '#005500',
        brightRed: '#33ff66',
        brightGreen: '#33ff66',
        brightYellow: '#33ff66',
        brightBlue: '#00ff41',
        brightMagenta: '#00cc33',
        brightCyan: '#33ff66',
        brightWhite: '#66ff88',
    },
    synthwave: {
        background: '#2b213a',
        foreground: '#f0e4fc',
        cursor: '#72f1b8',
        selectionBackground: '#463465',
        black: '#2b213a',
        red: '#fe4450',
        green: '#72f1b8',
        yellow: '#fede5d',
        blue: '#2ee2fa',
        magenta: '#ff7edb',
        cyan: '#03edf9',
        white: '#f0e4fc',
        brightBlack: '#614d85',
        brightRed: '#fe4450',
        brightGreen: '#72f1b8',
        brightYellow: '#fede5d',
        brightBlue: '#2ee2fa',
        brightMagenta: '#ff7edb',
        brightCyan: '#03edf9',
        brightWhite: '#ffffff',
    },
    highContrastDark: {
        background: '#000000',
        foreground: '#ffffff',
        cursor: '#ffffff',
        selectionBackground: '#264f78',
        selectionForeground: '#ffffff',
        black: '#000000',
        red: '#ff0000',
        green: '#00ff00',
        yellow: '#ffff00',
        blue: '#3b78ff',
        magenta: '#ff00ff',
        cyan: '#00ffff',
        white: '#ffffff',
        brightBlack: '#808080',
        brightRed: '#ff3333',
        brightGreen: '#33ff33',
        brightYellow: '#ffff33',
        brightBlue: '#6699ff',
        brightMagenta: '#ff33ff',
        brightCyan: '#33ffff',
        brightWhite: '#ffffff',
    },
} as DefaultThemesType;

DefaultThemes.yellow = DefaultThemes.highContrastLight;

export * from './theme-info';

import type { CliThemeInfo } from './theme-info';

export const DefaultThemeInfos: Record<string, CliThemeInfo> = {
    default: {
        theme: DefaultThemes.default,
        category: 'dark',
        tags: ['built-in'],
        description: 'Default terminal palette',
    },
    dracula: {
        theme: DefaultThemes.dracula,
        category: 'dark',
        tags: ['popular'],
        description: 'Popular dark theme with vibrant colors',
    },
    monokai: {
        theme: DefaultThemes.monokai,
        category: 'dark',
        tags: ['popular'],
        description: 'Classic code editor dark theme',
    },
    solarizedDark: {
        theme: DefaultThemes.solarizedDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Ethan Schoonover\'s precision dark palette',
    },
    solarizedLight: {
        theme: DefaultThemes.solarizedLight,
        category: 'light',
        tags: ['popular'],
        description: 'Ethan Schoonover\'s precision light palette',
    },
    gruvboxDark: {
        theme: DefaultThemes.gruvboxDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Retro groove dark color scheme',
    },
    gruvboxLight: {
        theme: DefaultThemes.gruvboxLight,
        category: 'light',
        tags: ['popular'],
        description: 'Retro groove light color scheme',
    },
    nord: {
        theme: DefaultThemes.nord,
        category: 'dark',
        tags: ['popular'],
        description: 'Arctic, north-bluish clean palette',
    },
    oneDark: {
        theme: DefaultThemes.oneDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Atom\'s iconic dark theme',
    },
    material: {
        theme: DefaultThemes.material,
        category: 'dark',
        tags: ['popular'],
        description: 'Material Design inspired dark theme',
    },
    highContrastLight: {
        theme: DefaultThemes.highContrastLight,
        category: 'light',
        tags: ['accessibility'],
        description: 'High contrast light theme for accessibility',
    },
    tokyoNight: {
        theme: DefaultThemes.tokyoNight,
        category: 'dark',
        tags: ['popular'],
        description: 'Cool blue-purple dark theme',
    },
    catppuccinMocha: {
        theme: DefaultThemes.catppuccinMocha,
        category: 'dark',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel dark theme (warmest)',
    },
    catppuccinFrappe: {
        theme: DefaultThemes.catppuccinFrappe,
        category: 'dark',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel mid-dark theme',
    },
    catppuccinLatte: {
        theme: DefaultThemes.catppuccinLatte,
        category: 'light',
        tags: ['popular', 'pastel'],
        description: 'Soothing pastel light theme',
    },
    rosePine: {
        theme: DefaultThemes.rosePine,
        category: 'dark',
        tags: ['popular'],
        description: 'All natural pine, faux fur, and a bit of soho vibes',
    },
    rosePineDawn: {
        theme: DefaultThemes.rosePineDawn,
        category: 'light',
        tags: ['popular'],
        description: 'Rose Pine light variant',
    },
    kanagawa: {
        theme: DefaultThemes.kanagawa,
        category: 'dark',
        tags: ['popular'],
        description: 'Dark theme inspired by Katsushika Hokusai',
    },
    everforestDark: {
        theme: DefaultThemes.everforestDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Comfortable green-tinted dark theme',
    },
    everforestLight: {
        theme: DefaultThemes.everforestLight,
        category: 'light',
        tags: ['popular'],
        description: 'Comfortable green-tinted light theme',
    },
    ayuDark: {
        theme: DefaultThemes.ayuDark,
        category: 'dark',
        tags: ['popular'],
        description: 'Simple, bright and elegant dark theme',
    },
    githubLight: {
        theme: DefaultThemes.githubLight,
        category: 'light',
        tags: ['popular'],
        description: 'GitHub\'s clean light interface theme',
    },
    cyberpunk: {
        theme: DefaultThemes.cyberpunk,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Neon-lit cyberpunk aesthetic',
    },
    retroGreen: {
        theme: DefaultThemes.retroGreen,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Classic green phosphor CRT monitor',
    },
    retroAmber: {
        theme: DefaultThemes.retroAmber,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Warm amber CRT monitor',
    },
    matrix: {
        theme: DefaultThemes.matrix,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: 'Enter the Matrix - green on black',
    },
    synthwave: {
        theme: DefaultThemes.synthwave,
        category: 'dark',
        tags: ['retro', 'fun'],
        description: '80s synthwave purple/pink aesthetic',
    },
    highContrastDark: {
        theme: DefaultThemes.highContrastDark,
        category: 'dark',
        tags: ['accessibility'],
        description: 'Maximum contrast dark theme',
    },
};
